[package]
name = "rs-std-net-windows"
version = "0.1.0"
authors = ["Damon Barry <damonb@microsoft.com>"]

[dependencies]
cfg-if = "0.1"
libc = "0.2"
winapi = { version = "0.3", features = ["ntdef", "winsock2", "ws2def"] }

[dev-dependencies]
rand = "0.4"